## Task - 12 (Day - 13)

## Create arrays with all the data types available in numpy

## Available data types in munpy

* integer
* boolean
* unsigned integer
* float
* complex float
* timedelta
* datetime
* object
* string
* unicode string
* void

In [3]:
import numpy as np

In [5]:
a = np.array([3,4,5,6])
print(a,a.dtype)

[3 4 5 6] int32


In [7]:
a = np.array([3,4,5,6], dtype='bool_')
print(a,a.dtype)

[ True  True  True  True] bool


In [8]:
a = np.array([3,4,5,6], dtype='uint32')
print(a,a.dtype)

[3 4 5 6] uint32


In [9]:
a = np.array([3,4,5,6], dtype='float32')
print(a,a.dtype)

[3. 4. 5. 6.] float32


In [10]:
a = np.array([3,4,5,6], dtype='complex_')
print(a,a.dtype)

[3.+0.j 4.+0.j 5.+0.j 6.+0.j] complex128


In [11]:
a = np.timedelta64(1,'D')
print(a,a.dtype)

1 days timedelta64[D]


In [12]:
a = np.array(['2002-07-03','2008-07-16','2006-03-20'], dtype='datetime64')
a

array(['2002-07-03', '2008-07-16', '2006-03-20'], dtype='datetime64[D]')

In [13]:
a = np.array([3,4,5,6], dtype='O')
print(a,a.dtype)

[3 4 5 6] object


In [14]:
a = np.array(['Hello','Hi','How are you'])
print(a,a.dtype)

['Hello' 'Hi' 'How are you'] <U11


In [25]:
a = np.array([u'\265E', u'\265F'], dtype='U')
a

array(['µE', 'µF'], dtype='<U2')

TypeError: void() takes at most 1 argument (2 given)